import { DAY } from '../constants';

export const config = {
	query: {
		staleTime: DAY,
		cacheTime: DAY,
	},
	metaApi: {
		url: import.meta.env.VITE_THOTH_API_URL ?? 'https://api.thoth.pub/graphql',
		itemsPerRequestLimit: 100,
	},
	metricsApi: {
		url:
			import.meta.env.VITE_METRICS_API_URL ??
			'https://metrics-api.operas-eu.org',
		dateFormat: 'YYYY-MM-DD',
		itemsPerRequestLimit: 30,
		trackedMetrics: [
			'https://metrics.operas-eu.org/google-books/views/v1',
			'https://metrics.operas-eu.org/obp-html/sessions/v1',
			'https://metrics.operas-eu.org/obp-pdf/sessions/v1',
			'https://metrics.operas-eu.org/obp/downloads/v1',
			'https://metrics.operas-eu.org/world-reader/users/v1',
			'https://metrics.operas-eu.org/open-edition/views/v1',
			'https://metrics.operas-eu.org/open-edition/downloads/v1',
			'https://metrics.operas-eu.org/oapen/downloads/v1',
			'https://metrics.operas-eu.org/jstor/views/v1',
			'https://metrics.operas-eu.org/jstor/downloads/v1',
			'https://metrics.operas-eu.org/classics-library/sessions/v1',
			'https://metrics.operas-eu.org/unglueit/downloads/v1',
			'https://metrics.operas-eu.org/openaire/downloads/v1',
			'https://metrics.operas-eu.org/wikimedia/views/v1',
			'https://metrics.operas-eu.org/sub-gottingen/downloads/v1',
			'https://metrics.operas-eu.org/ekt/downloads/v1',
			'https://metrics.operas-eu.org/ekt/sessions/v1',
			'https://metrics.operas-eu.org/ekt/landingsessions/v1',
			'https://metrics.operas-eu.org/wikipedia/references/v1',
			'https://metrics.operas-eu.org/wordpress/references/v1	',
			'https://metrics.operas-eu.org/figshare/views/v1',
			'https://metrics.operas-eu.org/figshare/downloads/v1',
			'https://metrics.operas-eu.org/figshare/shares/v1',
			'https://metrics.operas-eu.org/uplo/sessions/v1',
			'https://metrics.operas-eu.org/uplo/reads/v1',
			'https://metrics.operas-eu.org/uplo/downloads/v1',
			'https://metrics.operas-eu.org/historical/downloads/v1',
		],
		excludedPlatforms: ['ubiquity press', 'hypothesis'],
	},
	charts: {
		defaultHeight: 350,
		defaultColors: [
			'#5b65cf',
			'#efdaae',
			'#efdaae',
			'#5fb0d3',
			'#8da0f1',
			'#8da0f1',
			'#8da0f1',
			'#fede75',
			'#fede75',
			'#88f286',
			'#f2e986',
			'#db6a6a',
			'#5bcfbd',
			'#c160cc',
			'#52a46b',
		],
		timeMetricsChart: {
			maxYearsPerPage: 15,
		},
		labelSeparator: ' - ',
		timeMetricsChartLabelSeparator: ' · ',
		defaultKeys: [
			'The Classics Library - sessions',
			'Google Books - reads',
			'Google Books - views',
			'OAPEN - downloads',
			'OBP - downloads',
			'OBP HTML Reader - sessions',
			'OBP PDF Reader - sessions',
			'Open Edition - downloads',
			'Open Edition - views',
			'Twitter - tweets',
			'Wikimedia - views',
			'Wikipedia - references',
			'WordPress.com - references',
			'World Reader - users',
			'Crossref - citations',
		],
		mapChart: {
			countriesListLimit: 10,
		},
	},
	timers: {
		defaultDelayInMs: 3000,
	},
};
